Repository Help-M-Ssaem/back-end, pull requests merged in 2023-07, with the labels that each got.

#3 Exception Handler 설정
  src/main/java/com/example/mssaem_backend/global/config/exception/BaseException.java
  src/main/java/com/example/mssaem_backend/global/config/exception/ControllerAdvice.java
  src/main/java/com/example/mssaem_backend/global/config/exception/ErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/ExceptionResponse.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/GlobalErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/MemberErrorCode.java
Labels: Infra

#35 Spring Security 설정
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Role.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/refreshtoken/RefreshToken.java
  src/main/java/com/example/mssaem_backend/domain/refreshtoken/RefreshTokenController.java
  src/main/java/com/example/mssaem_backend/domain/refreshtoken/RefreshTokenRepository.java
  src/main/java/com/example/mssaem_backend/domain/refreshtoken/RefreshTokenService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/AuthErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/security/SecurityConfig.java
  src/main/java/com/example/mssaem_backend/global/config/security/auth/CurrentMember.java
  src/main/java/com/example/mssaem_backend/global/config/security/auth/CustomAccessDeniedHandler.java
  src/main/java/com/example/mssaem_backend/global/config/security/auth/PrincipalDetails.java
  src/main/java/com/example/mssaem_backend/global/config/security/auth/PrincipalDetailsService.java
  src/main/java/com/example/mssaem_backend/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mssaem_backend/global/config/security/jwt/JwtExceptionFilter.java
  src/main/java/com/example/mssaem_backend/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/Converter.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginType.java
Labels: Feature, Infra

#34 평가 관련 API 구현
  .gitignore
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/Evaluation.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationController.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationEnum.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationRepository.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationService.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/dto/EvaluationRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/dto/EvaluationResultDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/test/java/com/example/mssaem_backend/domain/evaluation/EvaluationControllerTest.java
Labels: Feature

#45 채팅과 관련된 Entity 교체
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
Labels: Documentation

#43 회원가입 API
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/CommonController.java
  src/main/java/com/example/mssaem_backend/global/config/exception/BaseException.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/MemberErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/KakaoLoginService.java
Labels: Feature

#40 고민글 조회 관련 API
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
  src/main/java/com/example/mssaem_backend/global/common/Time.java
  src/main/java/com/example/mssaem_backend/global/common/dto/PageResponseDto.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/WorryBoardErrorCode.java
  src/test/java/com/example/mssaem_backend/domain/worryboard/WorryBoardControllerTest.java
Labels: Feature

#41 HOT 게시판 더보기 API
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/Time.java
  src/main/java/com/example/mssaem_backend/global/common/dto/PageResponseDto.java
Labels: Feature

#42 홈 화면 조회 - HOT 게시판 API
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
Labels: Feature

#50 토론 관련 Entity 추가
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOption.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelected.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedController.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedService.java
Labels: Documentation

#51 Main merge
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOption.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelected.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedController.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedService.java
Labels: Main Merge

#52 HOT 게시판 더보기 API 수정
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImage.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
Labels: Bug

#54 Main merge
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImage.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/bookmark/BookMark.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOption.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelected.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/Evaluation.java
  src/main/java/com/example/mssaem_backend/domain/like/Like.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/notification/Notification.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImage.java
  src/main/java/com/example/mssaem_backend/global/config/webconfig/WebConfig.java
Labels: Main Merge

#62 Entity 수정
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImage.java
  src/main/java/com/example/mssaem_backend/domain/bookmark/BookMark.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/Evaluation.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/notification/Notification.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImage.java
Labels: Documentation

#59 평가 관련 API에 유저 권한 추가
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationController.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationService.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/dto/EvaluationResultDto.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
Labels: Feature

#58 HOT 토론 더보기 API
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOptionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/dto/DiscussionOptionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
Labels: Feature

#61 홈 화면 조회 - HOT 토론 API
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
Labels: Feature

#64 Main merge
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImage.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageService.java
  src/main/java/com/example/mssaem_backend/domain/bookmark/BookMark.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOptionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/dto/DiscussionOptionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelected.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/Evaluation.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationController.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationService.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/dto/EvaluationResultDto.java
  src/main/java/com/example/mssaem_backend/domain/like/Like.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/domain/notification/Notification.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImage.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/BoardErrorCode.java
Labels: Main Merge

#65 HOT 게시판/토론 관련 수정사항
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
Labels: Bug

#69 홈 화면 조회 - M쌤 매칭을 기다리는 고민 API
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Feature

#74 홈 화면 조회 - 인기 M쌤
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
Labels: Documentation, Feature

#66 채팅방 관련 API V2
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/chat/ChatController.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatMessageDto.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageController.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageResourceDto.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateController.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/com/example/mssaem_backend/global/config/redis/EmbeddedRedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisPublisher.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisSubscriber.java
  src/main/java/com/example/mssaem_backend/global/config/webconfig/WebConfig.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/WebSocketConfig.java
Labels: Feature

#76 홈 화면 조회 - 3HOT
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
Labels: Feature

#85 채팅방 모두 조회
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateController.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/BaseTimeEntity.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
Labels: Feature

#80 고민글 생성/수정/삭제/완료 API
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImage.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
  src/test/java/com/example/mssaem_backend/domain/worryboard/WorryBoardControllerTest.java
Labels: Feature

#86 Main merge 9회차
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatController.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatMessageDto.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageController.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageResourceDto.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateController.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImage.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
  src/main/java/com/example/mssaem_backend/global/common/BaseTimeEntity.java
  src/main/java/com/example/mssaem_backend/global/config/redis/EmbeddedRedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisPublisher.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisSubscriber.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/WebSocketConfig.java
  src/test/java/com/example/mssaem_backend/domain/worryboard/WorryBoardControllerTest.java
Labels: Main Merge

#91 카카오 소셜 로그인 API
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/AuthErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/GoogleLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/KakaoLoginService.java
Labels: Feature

#92 Main merge 10회차
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLike.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeController.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLike.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeService.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/search/Search.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchController.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/AuthErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/GoogleLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/KakaoLoginService.java
Labels: Main Merge

#93 Main merge 11회차
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
Labels: Main Merge

#88 멤버 정보 조회시 Mbti 대소문자 구별
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
Labels: Refactoring

#90 Repository 리팩토링
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImage.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
Labels: Refactoring

#97 게시글 수정, 삭제 관련수정
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
Labels: Bug

#99 Refactor : member 수정/삭제 권한 부여 코드 중복 해결
  src/main/java/com/example/mssaem_backend/global/common/CheckWriter.java
Labels: Refactoring

#94 구글 소셜 로그인 구현
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/KakaoLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
Labels: Feature

#101 토론 검색하기 API
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchRequestDto.java
Labels: Feature

#103 고민 검색하기 API
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Feature

#104 전체 게시판과 Mbti 카테고리 별 검색하기 API 하나로 병합
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
Labels: Refactoring

#109 토론글 생성, 수정, 삭제 API
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOption.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOptionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOptionService.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/dto/DiscussionOptionRequestDto.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/DiscussionErrorCode.java
Labels: Feature

#107 게시글 상세 조회 시 좋아요 눌렀는지 확인
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
Labels: Feature

#105 게시글 댓글 조회 API
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
Labels: Documentation, Feature

#116 Main 에러 해결
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
Labels: Main Merge

#118 게시글 이미지 업로드 API
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageController.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageService.java
  src/main/java/com/example/mssaem_backend/global/s3/S3Service.java
Labels: Feature

#120 Fix : 게시글 수정 시 썸네일 변경 수정 및 게시글 상세 조회시 MBTI 추가
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
Labels: Refactoring

#121 채팅방 입장, 퇴장 API 구현
  src/main/java/com/example/mssaem_backend/domain/chat/ChatController.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatMessageDto.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisPublisher.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisSubscriber.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Feature

#122 게시글 베스트 댓글 조회 API
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
Labels: Feature

#124 게시글 댓글 생성, 삭제 / 댓글 좋아요 누르기 API
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLike.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeController.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeService.java
Labels: Feature

#123 토론 참여하기 API
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOption.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelected.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/DiscussionErrorCode.java
Labels: Feature

#125 Main merger 14회차
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLike.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeController.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeService.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatController.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatMessageDto.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOption.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelected.java
  src/main/java/com/example/mssaem_backend/domain/discussionoptionselected/DiscussionOptionSelectedRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/DiscussionErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisPublisher.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisSubscriber.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Main Merge
