Repository Help-M-Ssaem/back-end, pull requests merged in 2023-08, with the labels that each got.

#126 신고하기 API
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/domain/report/Report.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportContent.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportController.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportRepository.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportService.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportType.java
  src/main/java/com/example/mssaem_backend/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/global/config/exception/ControllerAdvice.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/BoardCommentErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/DiscussionCommentErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ReportError.java
Labels: Feature

#129 전체 검색 API
  src/main/java/com/example/mssaem_backend/MssaemBackendApplication.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/search/Search.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchController.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
Labels: Feature

#130 프로필 조회와 수정 API
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/badge/dto/BadgeResponse.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/GoogleLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
  src/test/java/com/example/mssaem_backend/domain/worryboard/WorryBoardControllerTest.java
Labels: Feature

#131 Main merge 15회차
  build.gradle
  src/main/java/com/example/mssaem_backend/MssaemBackendApplication.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/badge/dto/BadgeResponse.java
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/report/Report.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportContent.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportController.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportRepository.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportService.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportType.java
  src/main/java/com/example/mssaem_backend/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/search/Search.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchController.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
  src/main/java/com/example/mssaem_backend/global/config/exception/ControllerAdvice.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/BoardCommentErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/DiscussionCommentErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ReportError.java
  src/main/java/com/example/mssaem_backend/global/config/redis/RedisConfig.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/GoogleLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
  src/test/java/com/example/mssaem_backend/domain/worryboard/WorryBoardControllerTest.java
Labels: Main Merge

#132 최근 검색어 및 실시간 인기 검색어
  src/main/java/com/example/mssaem_backend/domain/search/SearchController.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchResponseDto.java
Labels: Feature

#137 토론글 조회/댓글 관련 API
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLike.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeService.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/dto/DiscussionOptionResponseDto.java
Labels: Feature

#138 알림 관련 API
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeService.java
  src/main/java/com/example/mssaem_backend/domain/notification/Notification.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationController.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationRepository.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
  src/main/java/com/example/mssaem_backend/domain/notification/TypeEnum.java
  src/main/java/com/example/mssaem_backend/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/Time.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/NotificationErrorCode.java
Labels: Feature

#139 Main merge 16회차
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/dto/DiscussionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLike.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncommentlike/DiscussionCommentLikeService.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/dto/DiscussionOptionResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeService.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/notification/Notification.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationController.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationRepository.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
  src/main/java/com/example/mssaem_backend/domain/notification/TypeEnum.java
  src/main/java/com/example/mssaem_backend/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchController.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/Time.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/NotificationErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
  src/main/resources/help-m-ssaem-firebase-adminsdk-o62td-54433a44b6.json
Labels: Main Merge

#134 특정 멤버별 게시판 댓글 조회 API
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
Labels: Feature

#147 채팅방 조회 및 채팅 메시지 Response 변경
  src/main/java/com/example/mssaem_backend/domain/chat/ChatController.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageResourceDto.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatMessageErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomParticipateErrorCode.java
Labels: Feature, Refactoring

#142 고민글 파일 업로드 API 분리
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageController.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
Labels: Feature

#144 게시글 조회시 최신순으로 변경 / 댓글 작성 시 반환 값 수정
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
Labels: Refactoring

#148 Main merger 17회차
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatController.java
  src/main/java/com/example/mssaem_backend/domain/chat/ChatService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageResourceDto.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageController.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatMessageErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomParticipateErrorCode.java
Labels: Main Merge

#149 게시글 삭제 시 게시글 좋아요 / 댓글 좋아요/ 댓글 모두 삭제
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
Labels: Feature

#153 Fix : 특정 멤버별 토론 댓글 조회
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
Labels: Feature

#156 게시글 댓글 삭제시 좋아요 삭제 / 토론글 댓글 관련 Refactor
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
Labels: Feature, Refactoring

#158 고민 게시글 결과 값 리팩토링
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Refactoring

#160 Fix: 전체 게시글 조회 시 최신순으로 조회
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
Labels: Bug

#163 Main merge 19회차
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/domain/search/dto/SearchResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Main Merge

#165 Fix: 게시글 좋아요 누를 시 유효성 검사
  src/main/java/com/example/mssaem_backend/domain/like/LikeService.java
Labels: Refactoring

#166 멤버 프로필 관련 API
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/badge/dto/BadgeResponse.java
  src/main/java/com/example/mssaem_backend/domain/mbti/MbtiEnum.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/BadgeErrorCode.java
Labels: Feature, Refactoring

#172 자신의 채팅방 조회 결과 변경
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
Labels: Documentation, Change

#170 HOT 기준 변경
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
Labels: Change

#174 채팅방 에러 해결 v1
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomParticipateErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Bug

#175 Main merge 21회차
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/search/SearchService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomParticipateErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Main Merge

#176 Main merge 배포 에러 해결
  src/main/java/com/example/mssaem_backend/domain/member/dto/MemberResponseDto.java
Labels: Main Merge

#181 채팅방 삭제 API
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Feature

#178 게시글 좋아요 오류 수정
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeService.java
Labels: Bug

#183 채팅 메시지 모두 전송
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessage.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageController.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageService.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/dto/ChatMessageResourceDto.java
Labels: Feature

#186 알림 조회시 type 명시 및 수정
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
  src/main/java/com/example/mssaem_backend/domain/notification/TypeEnum.java
  src/main/java/com/example/mssaem_backend/domain/notification/dto/NotificationResponseDto.java
Labels: Change

#187 게시판 별 게시글 개수 조회
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
Labels: Feature

#190 게시판/고민글 댓글 통합
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/Comment.java
  src/main/java/com/example/mssaem_backend/global/common/CommentService.java
  src/main/java/com/example/mssaem_backend/global/common/CommentTypeEnum.java
  src/main/java/com/example/mssaem_backend/global/common/dto/CommentDto.java
Labels: Refactoring

#191 댓글 작성, 삭제 시 commentCount 변경
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/global/common/CommentService.java
Labels: Feature, Change

#192 Main merge 22회차
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentController.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentService.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcommentlike/BoardCommentLikeRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/Comment.java
  src/main/java/com/example/mssaem_backend/global/common/CommentService.java
  src/main/java/com/example/mssaem_backend/global/common/CommentTypeEnum.java
  src/main/java/com/example/mssaem_backend/global/common/dto/CommentDto.java
Labels: Main Merge

#195 채팅방 에러 해결
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomParticipateErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Bug, Change

#197 프로필 이미지 등록 API 분리 구현
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/MemberErrorCode.java
Labels: Feature

#196 기타 신고 사유 Enum 추가 및 에러 수정
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/report/Report.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportReason.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportRepository.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportService.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportTarget.java
  src/main/java/com/example/mssaem_backend/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
Labels: Bug, Change

#198 Main merge 22회차
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardComment.java
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
  src/main/java/com/example/mssaem_backend/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/report/Report.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportReason.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportRepository.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportService.java
  src/main/java/com/example/mssaem_backend/domain/report/ReportTarget.java
  src/main/java/com/example/mssaem_backend/domain/report/dto/ReportRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomParticipateErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/MemberErrorCode.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Main Merge

#199 Main merge 배포 에러 해결
  src/main/java/com/example/mssaem_backend/domain/discussion/Discussion.java
Labels: Bug, Main Merge

#202 채팅방 생성 및 채팅방 모두 조회 결과 변경
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomController.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomCustomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomRequestDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/dto/ChatRoomResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Documentation, Feature

#207 채팅방 상태 조회 API 변경
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomErrorCode.java
Labels: Feature, Change

#208 Main merge 24회차
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/global/config/exception/errorCode/ChatRoomErrorCode.java
Labels: Main Merge

#210 고민글 상세조회에 채팅방 아이디 추가
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Documentation, Change

#215 채팅방 제목 수정 및 각 채팅방 최근 채팅 출력
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateController.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
Labels: Bug, Change

#213 구글 소셜 로그인 구현 및 소셜 로그인 리팩토링
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/GoogleSocialLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/KaKaoSocialLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/NaverSocialLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
Labels: Bug, Feature

#222 Member 엔티티의 DefaultProfile 필드에 @transient 제거
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
Labels: Change

#219 댓글 조회 오류 수정
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/global/common/dto/CommentDto.java
Labels: Bug, Documentation

#221 Main merge 24회차
  src/main/java/com/example/mssaem_backend/domain/boardcomment/BoardCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatmessage/ChatMessageRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipate.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateController.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoom.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionComment.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentController.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/DiscussionCommentRepository.java
  src/main/java/com/example/mssaem_backend/domain/member/Member.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/global/common/Time.java
  src/main/java/com/example/mssaem_backend/global/common/dto/CommentDto.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/GoogleSocialLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/KaKaoSocialLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/NaverSocialLoginService.java
  src/main/java/com/example/mssaem_backend/global/config/security/oauth/SocialLoginService.java
Labels: Main Merge

#226 게시글 / 고민글 상세 조회 시 조회수 상승 및 조회수 출력
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Documentation, Feature

#227 고민/토론글 조회 쿼리 수정
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
Labels: Change

#230 Main merge 25회차
  src/main/java/com/example/mssaem_backend/domain/board/Board.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/board/dto/BoardResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/boardcomment/dto/BoardCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionController.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionRepository.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/discussioncomment/dto/DiscussionCommentResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoard.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Main Merge

#235 해결 완료 처리 시 response 수정
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Change

#236 긴급 콜택시 (Main)
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/like/LikeService.java
  src/main/java/com/example/mssaem_backend/domain/notification/Notification.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationType.java
  src/main/java/com/example/mssaem_backend/domain/notification/dto/NotificationResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
  src/main/java/com/example/mssaem_backend/global/common/CommentService.java
Labels: Main Merge

#237 채팅방 조회 response 수정
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Change

#233 칭호 추가 API 구현
  src/main/java/com/example/mssaem_backend/domain/badge/Badge.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeEnum.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeRepository.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/discussion/DiscussionService.java
  src/main/java/com/example/mssaem_backend/domain/evaluation/EvaluationService.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/global/config/websocket/StompHandler.java
Labels: Feature

#240 파일 업로드 방식 변경
  src/main/java/com/example/mssaem_backend/domain/board/BoardController.java
  src/main/java/com/example/mssaem_backend/domain/board/BoardService.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardController.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageRepository.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
Labels: Documentation, Change

#241 알림 최신순으로 조회
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationRepository.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
Labels: Bug

#242 채팅방 조회에 고민 해결 상태 추가
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
Labels: Documentation

#243 긴급 main merge
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/dto/ChatParticipateResponseDto.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationRepository.java
  src/main/java/com/example/mssaem_backend/domain/notification/NotificationService.java
Labels: Main Merge

#246 대댓글 알림 중복 제거
  src/main/java/com/example/mssaem_backend/global/common/CommentService.java
Labels: Bug

#248 채팅 알림 받는 사람 수정
  src/main/java/com/example/mssaem_backend/domain/chatparticipate/ChatParticipateService.java
Labels: Bug

#250 긴급 main merge
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomRepository.java
  src/main/java/com/example/mssaem_backend/domain/chatroom/ChatRoomService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/WorryBoardService.java
  src/main/java/com/example/mssaem_backend/domain/worryboard/dto/WorryBoardResponseDto.java
Labels: Main Merge

#252 긴급 콜택시
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeEnum.java
  src/main/java/com/example/mssaem_backend/domain/badge/BadgeService.java
  src/main/java/com/example/mssaem_backend/domain/badge/dto/BadgeResponse.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
Labels: Main Merge

#256 사진 크기 재설정
  build.gradle
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageController.java
  src/main/java/com/example/mssaem_backend/domain/boardimage/BoardImageService.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOptionController.java
  src/main/java/com/example/mssaem_backend/domain/discussionoption/DiscussionOptionService.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberController.java
  src/main/java/com/example/mssaem_backend/domain/member/MemberService.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageController.java
  src/main/java/com/example/mssaem_backend/domain/worryboardimage/WorryBoardImageService.java
  src/main/java/com/example/mssaem_backend/global/s3/CustomMultipartFile.java
  src/main/java/com/example/mssaem_backend/global/s3/S3Service.java
  src/test/java/com/example/mssaem_backend/domain/evaluation/EvaluationControllerTest.java
Labels: Feature

#259 사진 원본 비율 유지
  src/main/java/com/example/mssaem_backend/global/s3/S3Service.java
Labels: Main Merge
